import React,{useEffect,useMemo,useRef,useState} from 'react';import {io} from 'socket.io-client';import{LayoutDashboard,Map,Train,TriangleAlert,BrainCircuit,ClipboardCheck,History,BarChart3,RefreshCw,Search,Check,X,Menu,Wifi,Clock,Activity,Plus,Trash2,Edit3}from'lucide-react';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000';
const get=async p=>{let r=await fetch(API+p);if(!r.ok)throw Error(await r.text());return r.json()};const post=async(p,b)=>{let r=await fetch(API+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return r.json()};
const SOCKET=import.meta.env.VITE_SOCKET_URL||'http://localhost:5000';
const nav=[['Dashboard',LayoutDashboard],['Train Monitor',Train],['Conflict Predictor',TriangleAlert],['AI Recommendations',BrainCircuit],['Decision History',History],['Analytics',BarChart3]];
function App(){const[controller,setController]=useState(null);const[page,setPage]=useState('Dashboard'),[data,setData]=useState({}),[loading,setLoading]=useState(false),[modal,setModal]=useState(null),[search,setSearch]=useState('');const socketRef=useRef(null);const load=async()=>{setLoading(true);try{let paths=['/api/analytics/dashboard','/api/network',controller?'/api/trains/area/'+encodeURIComponent(controller.area):'/api/trains','/api/conflicts','/api/recommendations','/api/controller-decisions'];let[a,n,t,c,r,d]=await Promise.all(paths.map(get));let scored=await get('/api/trains/scored');const areaRows=(t.data||[]).map(x=>({...x,delayPrevention:(scored.data||[]).find(y=>y.id===x.id)?.delayPrevention}));setData({analytics:a.data,network:n.data,trains:areaRows,conflicts:c.data,recs:r.data,decisions:d.data})}catch(e){setData(x=>({...x,error:'Backend connection failed. Check VITE_API_URL / backend port.'}))}setLoading(false)};useEffect(()=>{load();const s=io(SOCKET,{transports:['websocket','polling']});socketRef.current=s;s.on('telemetry',payload=>setData(x=>({...x,network:{...(x.network||{}),...payload},trains:payload.trains||x.trains})));s.on('conflicts',rows=>setData(x=>({...x,conflicts:rows})));return()=>s.close()},[controller]);const logout=()=>{localStorage.removeItem('railflow_controller');setController(null)};if(!controller)return <Login onLogin={setController}/>;let body=page==='Dashboard'?<Dashboard d={data} open={setModal} reload={load}/>:page==='Train Monitor'?<Trains rows={data.trains||[]} search={search} setSearch={setSearch} reload={load}/>:page==='Conflict Predictor'?<Conflicts rows={data.conflicts||[]}/>:page==='AI Recommendations'?<Recommendations rows={data.recs||[]} open={setModal} reload={load}/>:page==='Decision History'?<Decisions rows={data.decisions||[]}/>:<Analytics d={data.analytics}/>;return <div className="app"><aside><div className="brand">RailFlow <b>AI</b><small>AI-Powered Train Traffic Control</small></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)}><I/> {n}</button>)}</nav><div className="status"><span/> ALL SYSTEMS NORMAL<br/><small>AI + Backend Connected</small></div></aside><main><header><div><h1>{page}</h1><p>{controller.name} · {controller.area} · 15–20 assigned trains</p></div><div style={{display:'flex',gap:8}}><button className="outline" onClick={logout}>Sign Out</button><button className="refresh" onClick={load}><RefreshCw className={loading?'spin':''}/> Refresh</button></div></header>{data.error&&<div className="error">{data.error}</div>}{body}</main>{modal&&<DecisionModal rec={modal} close={()=>setModal(null)} reload={load}/>}</div>}
const Card=({title,value,sub,kind='blue',icon:Icon})=><div className="card"><div><p>{title}</p><h2 className={kind}>{value??'—'}</h2><small>{sub}</small></div>{Icon&&<Icon className={kind}/>}</div>;
function Dashboard({d,open,reload}){
  let a=d.analytics||{},recs=d.recs||[],conf=d.conflicts||[],tr=d.trains||[];
  let r=recs[0];
  const why=r?.whyThisAction||r?.reasons||[
    r?.expectedImpact?.delayReduction!=null?`Delay reduced by ${Math.abs(r.expectedImpact.delayReduction)} mins`:'Delay reduction expected',
    r?.expectedImpact?.throughput!=null?`Throughput improves by ${r.expectedImpact.throughput}%`:'Improves section throughput',
    'Avoids downstream conflict',
    r?.recommendedTrain?`Priority considered for Train ${r.recommendedTrain}`:'Higher priority train considered'
  ];
  return <><div className="grid cards">
    <Card title="Active Trains" value={a.activeTrains} sub="Live network" icon={Train}/>
    <Card title="Active Conflicts" value={a.predictedConflicts} kind="red" sub="Needs attention" icon={TriangleAlert}/>
    <Card title="AI Recommendations" value={recs.length} kind="green" sub="Generated by AI" icon={BrainCircuit}/>
    <Card title="Controller Decisions" value={a.controllerDecisions} kind="purple" sub="Human-in-the-loop" icon={ClipboardCheck}/>
  </div>
  <div className="dash">
    <ActiveMonitor rows={d?.trains||d?.network?.trains||[]} reload={reload}/>
    <section className="panel action screenshot-action">
      <div className="panelhead"><h3>AI Recommended Action</h3><span className="recommended">✓ Recommended</span></div>
      {r?<><div className="action-body">
        <div className="action-main">
          <h2>{r.recommendedAction||`Allow Train ${r.recommendedTrain||''} to pass first`}</h2>
          <h4>Why this action?</h4>
          <div className="why-list">{why.slice(0,4).map((x,i)=><div key={i}><span>✓</span>{typeof x==='string'?x:(x?.reason||JSON.stringify(x))}</div>)}</div>
        </div>
        <div className="impact impact-card">
          <h4>Expected Impact</h4>
          <div><span>Delay Reduction</span><strong>{r.expectedImpact?.delayReduction!=null?`${r.expectedImpact.delayReduction>0?'-':''}${Math.abs(r.expectedImpact.delayReduction)} mins`:'—'}</strong></div>
          <div><span>Throughput</span><strong>{r.expectedImpact?.throughput!=null?`+${r.expectedImpact.throughput}%`:'—'}</strong></div>
          <div><span>Affected Trains</span><b>{r.expectedImpact?.affectedTrains??r.affectedTrains??'—'}</b></div>
          <div><span>Confidence</span><b>{Math.round((r.confidence||0)*100)}%</b></div>
          <div className="confidence-bar"><i style={{width:`${Math.round((r.confidence||0)*100)}%`}}/></div>
        </div>
      </div>
      <div className="action-buttons">
        <button className="primary" onClick={()=>open(r)}>Approve Recommendation</button>
        <button className="simulate" onClick={()=>open(r)}>Simulate Alternatives</button>
        <button className="reject outline-reject" onClick={()=>open({...r,_dialogAction:'REJECTED'})}>Reject</button>
      </div></>:<p>No recommendation yet. Generate one from AI Recommendations.</p>}
    </section>
  </div>
  <div className="three">
    <Table title="Upcoming Conflicts" rows={conf.slice(0,4)} cols={['Section','Trains','Severity']} render={x=><><td>{x.section}</td><td>{x.trainA?.name} ↔ {x.trainB?.name}</td><td><Badge v={x.severity}/></td></>}/>
    <Table title="Top Delayed Trains" rows={[...tr].sort((a,b)=>b.delay-a.delay)} cols={['Train','Section','Delay']} render={x=><><td>{x.name}</td><td>{x.section}</td><td className="red">+{x.delay}m</td></>}/>
    <Insights/>
  </div></>
}
function ActiveMonitor({rows=[],reload}){const[refreshing,setRefreshing]=useState(false);const refreshNetwork=async()=>{if(refreshing)return;setRefreshing(true);try{const r=await post('/api/simulator/refresh',{});if(!r.success)throw Error(r.message||'Refresh failed');await reload?.()}catch(e){alert('Live network refresh failed: '+e.message)}finally{setRefreshing(false)}};return <div className="active-monitor"><div className="live-monitor-head"><div><b>Live Train Operations</b><small>Automatically refreshed from the backend every 60 seconds.</small></div><div className="live-actions"><span><Wifi/> LIVE API</span><button className="network-refresh" onClick={refreshNetwork} disabled={refreshing}><RefreshCw className={refreshing?'spin':''}/>{refreshing?'Refreshing...':'Refresh Live Network'}</button></div></div><div className="live-train-list">{rows.length?rows.slice(0,6).map((t,i)=><div className="live-train-row" key={t.id||i}><div className="train-icon"><Train/></div><div className="live-train-main"><b>{t.name}</b><small>{t.trainNumber} · {t.trainType||'TRAIN'} · {t.section}</small></div><div className="live-train-location"><b>{t.currentStation||'Location updating'}</b><small>Next: {t.nextStation||t.nextStationInfo?.station||'—'}</small></div><div><span className={`badge ${(t.status||'').toLowerCase()==='running'?'active':'medium'}`}>{t.status||'UNKNOWN'}</span></div><div className="delay"><b>{t.delay||0} min</b><small>delay</small></div></div>):<div className="empty">No tracked trains available.</div>}</div></div>}
function Network({d}){return <ActiveMonitor rows={d?.trains||[]}/>}
function Trains({rows,search,setSearch,reload}){const[trainNo,setTrainNo]=useState('');const[adding,setAdding]=useState(false);let filtered=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));const add=async()=>{if(!trainNo.trim())return;setAdding(true);try{let r=await post('/api/trains/track',{trainNo:trainNo.trim()});if(!r.success)throw Error(r.message);setTrainNo('');await reload()}catch(e){alert('Train add failed: '+e.message)}finally{setAdding(false)}};return <section className="panel"><div className="panelhead"><div><h3>All Active Trains</h3><small>Backend automatically refreshes tracked trains and broadcasts movement.</small></div><div style={{display:'flex',gap:8,alignItems:'center'}}><label className="search"><Search/><input placeholder="Search train..." value={search} onChange={e=>setSearch(e.target.value)}/></label></div></div><div className="trackbar"><input value={trainNo} onChange={e=>setTrainNo(e.target.value)} placeholder="Enter train number once (e.g. 19038)"/><button className="primary" disabled={adding} onClick={add}><Plus/> {adding?'Tracking...':'Track Train'}</button></div><table><thead><tr><th>Train ID</th><th>Name</th><th>Status / Type</th><th>Current Section</th><th>Delay</th><th>Priority</th><th>Delay Prevention</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.id}</td><td><b>{x.name}</b></td><td><Badge v={x.trainType||x.status||'ACTIVE'}/></td><td>{x.section}</td><td className={x.delay?'red':'green'}>{x.delay?`+${x.delay} min`:'On time'}</td><td>{x.priority}</td><td><b>{x.delayPrevention?.score??'—'}/100</b><small style={{display:'block'}}>{x.delayPrevention?.level||''}</small><small>{x.delayPrevention?.reasons?.[0]||''}</small></td></tr>)}</tbody></table></section>}
function Conflicts({rows}){return <section className="panel"><div className="panelhead"><h3>Active Conflict Predictions</h3><span className="danger">{rows.length} ACTIVE</span></div><table><thead><tr><th>ID</th><th>Type / Location</th><th>Affected Trains</th><th>Time Gap</th><th>Probability</th><th>Severity</th></tr></thead><tbody>{rows.map(x=><tr><td>{x.id}</td><td>Section {x.section}</td><td>{x.trainA?.name} ↔ {x.trainB?.name}</td><td>{x.timeDifference} min</td><td>{Math.round(x.conflictProbability*100)}%</td><td><Badge v={x.severity}/></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</section>}
function Recommendations({rows,open,reload}){const gen=async()=>{await post('/api/recommendations/generate',{});reload()};return <><div className="toolbar"><div><h2>AI Recommendation Center</h2><p>Explainable suggestions require controller approval.</p></div><button className="primary" onClick={gen}><Plus/> Generate New Recommendation</button></div><div className="recs">{rows.map(r=><section className="panel rec"><div><Badge v={r.severity}/><h2>{r.recommendedAction}</h2><p>{r.reason}</p><div className="meta"><span>Train <b>{r.recommendedTrain}</b></span><span>Confidence <b>{Math.round(r.confidence*100)}%</b></span><span>Mode <b>{r.aiMode}</b></span></div></div><button className="outline" onClick={()=>open(r)}>Review & Decide</button></section>)}{!rows.length&&<section className="panel"><Empty text="No recommendations yet. Click Generate New Recommendation."/></section>}</div></>}
function DecisionModal({rec,close,reload}){
  const[note,setNote]=useState('');
  const[busy,setBusy]=useState(false);
  const impact=rec.expectedImpact||{};
  const why=rec.whyThisAction||rec.reasons||[
    impact.delayReduction!=null?`Delay reduced by ${Math.abs(impact.delayReduction)} mins`:'Delay reduction expected',
    impact.throughput!=null?`Throughput improves by ${impact.throughput}%`:'Improves section throughput',
    'Avoids downstream conflict'
  ];
  const save=async decision=>{
    setBusy(true);
    try{await post('/api/controller-decisions',{recommendationId:rec.id,conflictId:rec.conflictId||rec.id?.replace(/^AI-/,'RT-')||null,decision,selectedTrain:rec.recommendedTrain,controllerNote:note});reload();close()}
    catch(e){alert('Decision could not be saved. Check backend connection.')}
    finally{setBusy(false)}
  };
  return <div className="overlay"><div className="modal controller-modal">
    <button className="close" onClick={close}>×</button>
    <div className="modal-top"><div><span className="modal-kicker">CONTROLLER REVIEW</span><h2>Controller Decision</h2></div><span className="recommended">✓ AI Recommended</span></div>
    <h3>{rec.recommendedAction||`Allow Train ${rec.recommendedTrain||''} to pass first`}</h3>
    <div className="decision-details">
      <div className="modal-why"><h4>Why this action?</h4>{why.slice(0,4).map((x,i)=><p key={i}><span>✓</span>{typeof x==='string'?x:(x?.reason||JSON.stringify(x))}</p>)}</div>
      <div className="modal-impact"><h4>Expected Impact</h4><p>Delay Reduction <b>{impact.delayReduction!=null?`${impact.delayReduction>0?'-':''}${Math.abs(impact.delayReduction)} mins`:'—'}</b></p><p>Throughput <b>{impact.throughput!=null?`+${impact.throughput}%`:'—'}</b></p><p>Confidence <b>{Math.round((rec.confidence||0)*100)}%</b></p></div>
    </div>
    <label className="note-label">Controller Note <small>(optional)</small></label>
    <textarea placeholder="Add your operational decision note..." value={note} onChange={e=>setNote(e.target.value)}/>
    <div className="modalactions">
      <button className="cancel-btn" onClick={close}>Cancel</button>
      <button className="reject" disabled={busy} onClick={()=>save('REJECTED')}><X/> Reject</button>
      <button className="approve" disabled={busy} onClick={()=>save('APPROVED')}><Check/> {busy?'Saving...':'Approve Recommendation'}</button>
    </div>
  </div></div>
}function Decisions({rows}){return <section className="panel"><div className="panelhead"><h3>Controller Decision History</h3><span>{rows.length} TOTAL</span></div><table><thead><tr><th>Decision</th><th>Recommendation</th><th>Train</th><th>Controller Note</th><th>Timestamp</th></tr></thead><tbody>{rows.map(x=><tr><td><Badge v={x.decision}/></td><td>{x.recommendationId}</td><td>{x.recommendedTrain||'—'}</td><td>{x.controllerNote||'—'}</td><td>{new Date(x.timestamp).toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No controller decisions yet."/>}</section>}
function Analytics({d}){return <div className="analytics"><div className="grid cards"><Card title="Section Throughput" value={(d?.sectionThroughput??0)+'%'} kind="green" sub="Network efficiency" icon={Activity}/><Card title="Total Network Delay" value={(d?.totalDelay??0)+' min'} kind="orange" sub="All active trains" icon={Clock}/><Card title="On-Time Performance" value={(d?.onTimePerformance??0)+'%'} kind="purple" sub="Current estimate" icon={BarChart3}/><Card title="Critical Conflicts" value={d?.criticalConflicts??0} kind="red" sub="Highest severity" icon={TriangleAlert}/></div><section className="panel"><h3>Operational Analytics</h3><p>These metrics are fetched from <code>GET /api/analytics/dashboard</code> and update whenever the dashboard is refreshed.</p></section></div>}
function Table({title,rows,cols,render}){return <section className="panel smalltable"><div className="panelhead"><h3>{title}</h3></div><table><thead><tr>{cols.map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr>{render(x)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</section>};const Badge=({v})=><span className={'badge '+String(v||'').toLowerCase()}>{v||'ACTIVE'}</span>;const Empty=({text='No data available.'})=><div className="empty">{text}</div>;function Insights(){return <section className="panel insights"><h3>System Insights</h3><p>● AI monitors section occupancy and arrival windows.</p><p>● Recommendations always require controller approval.</p><p>● ML service is used when available, with rule fallback.</p></section>}
function Login({onLogin}){const[controllerId,setId]=useState('CTRL-DEL-001'),[password,setPassword]=useState('railflow123'),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{const r=await post('/api/auth/login',{controllerId,password});if(!r.success)throw Error(r.message);localStorage.setItem('railflow_controller',JSON.stringify(r.controller));onLogin(r.controller)}catch(e){setErr(e.message||'Login failed')}finally{setBusy(false)}};return <div className="login-wrap"><form className="login-card" onSubmit={submit}><div className="brand">RailFlow <b>AI</b><small>AI-Powered Train Traffic Control</small></div><h2>Controller Sign In</h2><p>Sign in to access your assigned railway control area.</p><label>Controller ID<input value={controllerId} onChange={e=>setId(e.target.value)} placeholder="CTRL-DEL-001"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary login-btn" disabled={busy}>{busy?'Signing in...':'Sign In'}</button><small>Demo: CTRL-DEL-001 / railflow123</small></form></div>}
export default App;
